// Generated by CoffeeScript 1.6.2
(function() {
  define(['jquery', 'jqm', 'backbone', 'marionette'], function($, jqm, Backbone, Marionette) {
    var Meshable, search;

    Meshable = new Backbone.Marionette.Application();
    Meshable.theme = "a";
    Meshable.rooturl = "http://imistaway.com";
    Meshable.current - (search = null);
    Meshable.current_units = "";
    Meshable.current_gateways = "";
    Meshable.currentDataObj = "";
    Meshable.refreshUnits = false;
    Meshable.addRegions({
      loginRegion: "#login",
      mainRegion: "#mainR",
      searchRegion: "#searchR",
      menuRegion: "#menuR"
    });
    $(document).on("click", "#refresh-btn", function() {
      return window.history.refresh();
    });
    $(document).on("click", "#back-btn", function() {
      return window.history.back();
    });
    Meshable.on("initialize:after", function(options) {
      $.mobile.autoInitializePage = false;
      $.mobile.pageContainer = $("body");
      $.mobile.ajaxEnabled = false;
      $.mobile.linkBindingEnabled = false;
      $.mobile.hashListeningEnabled = false;
      $.mobile.pushStateEnabled = true;
      $.mobile.loader.prototype.options.text = "loading";
      $.mobile.loader.prototype.options.textVisible = true;
      $.mobile.loader.prototype.options.theme = "c";
      return Backbone.history.start({
        root: window.location.protocol + "//" + window.location.host,
        pushState: false
      });
    });
    Meshable.changePage = function(page, direction) {
      $(page.el).attr("data-role", "page");
      $(page.el).attr("data-theme", Meshable.theme);
      $.mobile.changePage($(page.el), {
        changeHash: true,
        reverse: direction,
        transition: "fade"
      });
      return $("#locationbtnn").addClass('ui-btn-active');
    };
    Meshable.chooseLight = function(light) {
      if (light === "green") {
        return "https://s3.amazonaws.com/LynxMVC4-Bucket/green-light.png";
      } else if (light === "yellow") {
        return "https://s3.amazonaws.com/LynxMVC4-Bucket/yellow-light.png";
      } else if (light === "red") {
        return "https://s3.amazonaws.com/LynxMVC4-Bucket/red-light.png";
      } else {
        return "https://s3.amazonaws.com/LynxMVC4-Bucket/no-light.png";
      }
    };
    return Meshable;
  });

}).call(this);
