// Generated by CoffeeScript 1.6.2
(function() {
  var child, email, forever, i, server, spinUp, _i;

  forever = require("forever-monitor");

  email = require("emailjs");

  child = new Array;

  server = email.server.connect({
    host: "localhost",
    ssl: false
  });

  server.send({
    text: "New Uploader Precess Started",
    from: "Uploader <lewis@meshify.com>",
    to: "lewiswight@gmail.com, dane@meshify.com",
    cc: "",
    subject: "New Uploader Precess Started"
  }, function(err, message) {
    return console.log(err || message);
  });

  console.log("New Uploader Precess Started");

  spinUp = function(name) {
    var directory, directory2, i;

    i = name;
    name = name.toString();
    directory = "./tmp/log" + name + ".txt";
    directory2 = "./tmp/error" + name + ".txt";
    child[i] = new forever.Monitor("uploadprocessnode/start.js", {
      max: 100,
      silent: true,
      outFile: directory,
      errFile: directory2,
      options: []
    });
    console.log(name);
    child[i].on("restart", function() {
      server = email.server.connect({
        host: "localhost",
        ssl: false
      });
      server.send({
        text: "uploader: " + name + " has restarted",
        from: "you <lewis@meshify.com>",
        to: "lewiswight@gmail.com, dane@meshify.com",
        cc: "",
        subject: "uploader: " + name + " has restarted",
        attachment: [
          {
            data: "<html><i>Log File</i></html>",
            alternative: true
          }, {
            path: directory,
            type: "text file",
            name: "log.txt"
          }, {
            data: "<html><i>Error File</i></html>",
            alternative: true
          }, {
            path: directory2,
            type: "text file",
            name: "error.txt"
          }
        ]
      }, function(err, message) {
        return console.log(err || message);
      });
      return console.log("uploader: " + name + " has restarted");
    });
    child[i].on("exit", function() {
      server = email.server.connect({
        host: "localhost",
        ssl: false
      });
      server.send({
        text: "one of your " + name + " uploaders has exited permenantly",
        from: "Uploader <lewis@meshify.com>",
        to: "lewiswight@gmail.com, dane@meshify.com",
        cc: "",
        subject: "one of your " + name + " uploaders has exited permenantly"
      }, function(err, message) {
        return console.log(err || message);
      });
      return console.log("one of your " + name + " uploaders has exited permenantly");
    });
    return child[i].start();
  };

  for (i = _i = 0; _i <= 24; i = ++_i) {
    spinUp(i);
  }

}).call(this);
