// Generated by CoffeeScript 1.3.3
(function() {

  define(['jquery', 'jqm', 'backbone', 'underscore', 'marionette', 'Meshable', 'Events'], function($, jqm, Backbone, _, Marionette, Meshable, Events) {
    var dashboard, dashboardView, dashboards, dashboardsView, make_collection;
    make_collection = function() {
      var cModel, model, models, nodeCollection, _i, _len;
      models = JSON.parse("[{\"address\":\"123 Main Ave\",\"channelname\":\"energy cost\",\"post\":\"\",\"pre\":\"$\",\"status\":\"The status\",\"trafficlight\":\"green\",\"value\":\"1232\"},{\"address\":\"123 Main Ave\",\"channelname\":\"energy cost\",\"post\":\"\",\"pre\":\"$\",\"status\":\"The status\",\"trafficlight\":\"green\",\"value\":\"1232\"},{\"address\":\"123 Main Ave\",\"channelname\":\"energy cost\",\"post\":\"\",\"pre\":\"$\",\"status\":\"The status\",\"trafficlight\":\"green\",\"value\":\"1232\"},{\"address\":\"123 Main Ave\",\"channelname\":\"energy cost\",\"post\":\"\",\"pre\":\"$\",\"status\":\"The status\",\"trafficlight\":\"green\",\"value\":\"1232\"},{\"address\":\"123 Main Ave\",\"channelname\":\"energy cost\",\"post\":\"\",\"pre\":\"$\",\"status\":\"The status\",\"trafficlight\":\"green\",\"value\":\"1232\"},{\"address\":\"123 Main Ave\",\"channelname\":\"energy cost\",\"post\":\"\",\"pre\":\"$\",\"status\":\"The status\",\"trafficlight\":\"green\",\"value\":\"1232\"},{\"address\":\"123 Main Ave\",\"channelname\":\"energy cost\",\"post\":\"\",\"pre\":\"$\",\"status\":\"The status\",\"trafficlight\":\"green\",\"value\":\"1232\"},{\"address\":\"123 Main Ave\",\"channelname\":\"energy cost\",\"post\":\"\",\"pre\":\"$\",\"status\":\"The status\",\"trafficlight\":\"green\",\"value\":\"1232\"},{\"address\":\"123 Main Ave\",\"channelname\":\"energy cost\",\"post\":\"\",\"pre\":\"$\",\"status\":\"The status\",\"trafficlight\":\"green\",\"value\":\"1232\"},{\"address\":\"123 Main Ave\",\"channelname\":\"energy cost\",\"post\":\"\",\"pre\":\"$\",\"status\":\"The status\",\"trafficlight\":\"green\",\"value\":\"1232\"}]");
      nodeCollection = new dashboards;
      for (_i = 0, _len = models.length; _i < _len; _i++) {
        model = models[_i];
        cModel = new dashboard;
        nodeCollection.add(cModel.parse(model));
      }
      return nodeCollection;
    };
    dashboard = Backbone.Model.extend({
      initialize: function() {
        return this.set({
          trafficlight: Meshable.chooseLight(this.get('trafficlight'))
        });
      },
      defaults: {
        channelname: "Energy Costs",
        status: "",
        address: "123 Main St.",
        value: "1100.50",
        pre: "$",
        post: "",
        trafficlight: "green"
      }
    });
    dashboards = Backbone.Collection.extend({
      model: dashboard
    });
    dashboardView = Backbone.Marionette.ItemView.extend({
      initialize: function(dashboard) {
        return this.bindTo(this.model, "change", this.render);
      },
      template: '#dashboarditem-template',
      tagName: 'li',
      className: "list_item"
    });
    dashboardsView = Backbone.Marionette.CompositeView.extend({
      itemView: dashboardView,
      template: "#wrapper_dashboard",
      itemViewContainer: "ul",
      id: "dashboard",
      appendHtml: function(collectionView, itemView) {
        return collectionView.$("#dashboard_insert").append(itemView.el);
      }
    });
    return new dashboardsView({
      collection: make_collection()
    });
    /*myvent.on "router:appStart", ->
    		Meshable.loginRegion.close()
    		Meshable.addRegions
    			themeRegion: "#csstheme"
    			headerRegion: "#header"
    			col1Region: ".col1"
    			col2topRegion: ".col2top"
    			col2bottomRegion: ".col2bottom"
    			col3Region: ".col3"
    			col4Region: ".col4"
    			footerRegion: "#footer"
    		$('#header').css 'display', 'block'		
    		$('#footer').css 'display', 'block'
    		$('.colmask').css 'display', 'block'
    		dashboardsCollection = new dashboards
    		dashboardCompositeView = new dashboardsView
    			collection: dashboardsCollection
    		Meshable.col1Region.show dashboardCompositeView
    		Meshable.themeRegion.show 
    		Meshable.headerRegion.show 
    		Meshable.col2topRegion.show 
    		Meshable.col2bottomRegion.show 
    		Meshable.col3Region.show 
    		Meshable.col4Region.show 
    		Meshable.footerRegion.show
    */

  });

}).call(this);
