// Generated by CoffeeScript 1.6.2
(function() {
  var AngryCat, AngryCatView, AngryCats, AngryCatsView, MyApp;

  MyApp = new Backbone.Marionette.Application();

  MyApp.addRegions({
    mainRegion: "#content"
  });

  AngryCat = Backbone.Model.extend({
    rankUp: function() {
      return this.set({
        rank: this.get("rank") - 1
      });
    },
    rankDown: function() {
      return this.set({
        rank: this.get('rank') + 1
      });
    }
  });

  AngryCats = Backbone.Collection.extend({
    model: AngryCat,
    initialize: function(cats) {
      var rank, self;

      rank = 1;
      _.each(cats, function(cat) {
        cat.set("rank", rank);
        return ++rank;
      });
      self = this;
      MyApp.vent.on("rank:up", function(cat) {
        if (cat.get("rank") === 1) {
          return true;
        }
        self.rankUp(cat);
        return self.sort();
      });
      return MyApp.vent.on("rank:down", function(cat) {
        if (cat.get('rank') === self.size) {
          return true;
        }
        self.rankDown(cat);
        return self.sort();
      });
    },
    comparator: function(cat) {
      return cat.get("rank");
    },
    rankUp: function(cat) {
      var otherCat, rankToSwap;

      rankToSwap = cat.get('rank') - 1;
      otherCat = this.at(rankToSwap - 1);
      cat.rankUp();
      return otherCat.rankDown();
    },
    rankDown: function(cat) {
      var otherCat, rankToSwap;

      rankToSwap = cat.get('rank') + 1;
      otherCat = this.at(rankToSwap - 1);
      cat.rankDown();
      return otherCat.rankUp();
    }
  });

  AngryCatView = Backbone.Marionette.ItemView.extend({
    template: "#angry_cat-template",
    tagName: 'tr',
    className: 'angry_cat',
    events: {
      "click .rank_up img": "rankUp",
      "click .rank_down img": "rankDown"
    },
    rankUp: function() {
      return MyApp.vent.trigger("rank:up", this.model);
    },
    rankDown: function() {
      return MyApp.vent.trigger("rank:down", this.model);
    }
  });

  AngryCatsView = Backbone.Marionette.CompositeView.extend({
    tagName: "table",
    id: "angry_cats",
    className: "table-striped table-bordered",
    template: "#angry_cats-template",
    itemView: AngryCatView,
    appendHtml: function(collectionView, itemView) {
      return collectionView.$("tbody").append(itemView.el);
    }
  });

  MyApp.addInitializer(function(options) {
    var angryCatsView;

    angryCatsView = new AngryCatsView({
      collection: options.cats
    });
    return MyApp.mainRegion.show(angryCatsView);
  });

  $(document).ready(function() {
    var cats_list;

    cats_list = new AngryCats([
      new AngryCat({
        name: "Wet Cat",
        image_path: "assets/images/cat2.jpg"
      }), new AngryCat({
        name: "Bitey Cat",
        image_path: "assets/images/cat1.jpg"
      }), new AngryCat({
        name: "Surprised Cat",
        image_path: "assets/images/cat3.jpg"
      })
    ]);
    return MyApp.start({
      cats: cats_list
    });
  });

}).call(this);
