// Generated by CoffeeScript 1.6.2
(function() {
  define(['jquery', 'jqm', 'backbone', 'underscore', 'marionette', 'Meshable', 'Events'], function($, jqm, Backbone, _, Marionette, Meshable, Events) {
    var displayResults, gateway, gatewayCompView, gatewayView, gateways, make_collection;

    make_collection = function() {
      return window.forge.ajax({
        url: "http://devbuildinglynx.apphb.com/api/dashboard",
        dataType: "json",
        type: "GET",
        error: function(e) {
          return alert(e.content);
        },
        success: function(data) {
          var cModel, model, nodeCollection, _i, _len;

          nodeCollection = new dashboards;
          for (_i = 0, _len = data.length; _i < _len; _i++) {
            model = data[_i];
            cModel = new dashboard;
            nodeCollection.add(cModel.parse(model));
          }
          return nodeCollection;
        }
      });
      /*models = JSON.parse """[{"address":"123 Main Ave","channelname":"energy cost","post":"","pre":"$","status":"The status","trafficlight":"green","value":"1232"},{"address":"123 Main Ave","channelname":"energy cost","post":"","pre":"$","status":"The status","trafficlight":"green","value":"1232"},{"address":"123 Main Ave","channelname":"energy cost","post":"","pre":"$","status":"The status","trafficlight":"green","value":"1232"},{"address":"123 Main Ave","channelname":"energy cost","post":"","pre":"$","status":"The status","trafficlight":"green","value":"1232"},{"address":"123 Main Ave","channelname":"energy cost","post":"","pre":"$","status":"The status","trafficlight":"green","value":"1232"},{"address":"123 Main Ave","channelname":"energy cost","post":"","pre":"$","status":"The status","trafficlight":"green","value":"1232"},{"address":"123 Main Ave","channelname":"energy cost","post":"","pre":"$","status":"The status","trafficlight":"green","value":"1232"},{"address":"123 Main Ave","channelname":"energy cost","post":"","pre":"$","status":"The status","trafficlight":"green","value":"1232"},{"address":"123 Main Ave","channelname":"energy cost","post":"","pre":"$","status":"The status","trafficlight":"green","value":"1232"},{"address":"123 Main Ave","channelname":"energy cost","post":"","pre":"$","status":"The status","trafficlight":"green","value":"1232"}]"""
      		
      		nodeCollection = new dashboards
      		
      		for model in models
      			cModel = new dashboard
      			nodeCollection.add cModel.parse(model)
      		
      		return nodeCollection
      */

    };
    gateway = Backbone.Model.extend({
      initialize: function() {
        return this.set({
          trafficlight: "green"
        });
      },
      defaults: {
        trafficlight: "green"
      }
    });
    gateways = Backbone.Collection.extend({
      model: gateway
    });
    gatewayView = Backbone.Marionette.ItemView.extend({
      initialize: function(gateway) {
        return this.bindTo(this.model, "change", this.render);
      },
      template: '#gatewayitem-template',
      tagName: 'li',
      className: "list_item",
      id: "gatewayItm"
    });
    gatewayCompView = Backbone.Marionette.CompositeView.extend({
      itemView: gatewayView,
      template: "#wrapper_ul",
      itemViewContainer: "ul",
      appendHtml: function(collectionView, itemView) {
        return collectionView.$("#placeholder").append(itemView.el);
      }
    });
    Meshable.vent.on("goto:gateways", function(refresh) {
      var _this = this;

      if (!refresh && Meshable.current_gateways !== "") {
        displayResults(Meshable.current_gateways);
        return;
      }
      $.mobile.showPageLoadingMsg("a", "Loading", false);
      return window.forge.ajax({
        url: "http://devbuildinglynx.apphb.com/api/Locations",
        data: {
          term: "",
          systemTypes: "",
          problemStatuses: "",
          customGroups: "",
          pageIndex: 0,
          pageSize: 10
        },
        dataType: "json",
        type: "GET",
        error: function(e) {
          return alert("An error occurred on search... sorry!");
        },
        success: function(data) {
          var list, node, _i, _len;

          list = [];
          data = data.CurrentPageListItems;
          for (_i = 0, _len = data.length; _i < _len; _i++) {
            node = data[_i];
            list.push(node.gateway.macaddress);
          }
          if (data.isAuthenticated === false) {
            return myvent.trigger("auth:logout");
          } else if (data.length === 0) {
            return alert("No Results");
          } else {
            Meshable.current_gateways = data;
            return displayResults(data);
          }
        }
      });
    });
    Meshable.vent.on("search:gateways", function(sdata) {
      var _this = this;

      $.mobile.showPageLoadingMsg("a", "Loading", false);
      return window.forge.ajax({
        url: "http://devbuildinglynx.apphb.com/api/Locations",
        data: {
          term: sdata,
          systemTypes: "",
          problemStatuses: "",
          customGroups: "",
          pageIndex: 0,
          pageSize: 10
        },
        dataType: "json",
        type: "GET",
        error: function(e) {
          return alert("An error occurred on search... sorry!");
        },
        success: function(data) {
          data = data.CurrentPageListItems;
          if (data.isAuthenticated === false) {
            return myvent.trigger("auth:logout");
          } else if (data.length === 0) {
            $.mobile.hidePageLoadingMsg();
            alert("No Results");
            return Backbone.history.navigate("search", {
              replace: true,
              trigger: false
            });
          } else {
            return displayResults(data);
          }
        }
      });
    });
    return displayResults = function(data) {
      var cModel, gateView, model, nodeCollection, _i, _len;

      nodeCollection = new gateways;
      for (_i = 0, _len = data.length; _i < _len; _i++) {
        model = data[_i];
        cModel = new gateway;
        nodeCollection.add(cModel.parse(model));
      }
      gateView = new gatewayCompView({
        collection: nodeCollection
      });
      Meshable.currentpage = "gateways";
      gateView.render();
      $('#mainDiv').empty();
      $('#mainDiv').append($(gateView.el));
      $("#mainPage").trigger('create');
      $.mobile.hidePageLoadingMsg();
      $("[data-role=footer]").fixedtoolbar({
        tapToggle: true
      });
      $("[data-role=footer]").fixedtoolbar({
        tapToggleBlacklist: "a, button, tap, div, img, input, select, textarea, .ui-header-fixed, .ui-footer-fixed"
      });
      $("#mainPage a").removeClass('ui-btn-active');
      return $("#locationbtnn").addClass('ui-btn-active');
    };
  });

}).call(this);
