// Generated by CoffeeScript 1.6.2
(function() {
  define(['jquery', 'jqm', 'backbone', 'underscore', 'marionette', 'Meshable', 'Events', 'login', 'dashboard', 'search'], function($, jqm, Backbone, _, Marionette, Meshable, Events, login, dashboard, search) {
    var Routing;

    Routing = Backbone.Router.extend({
      routes: {
        "gateway/:id": "gateway",
        "": "home",
        "dashboard": "dashboard",
        "menu": "menu",
        "back": "back",
        "popupPanel": "popupPanel",
        "menu_back_btn": "menu_back_btn",
        "search": "search",
        "searching/:id": "searchterm",
        "gateways": "gateways",
        "page1": "page1",
        "ref-page": "refPage",
        "logout": "logout"
      },
      logout: function() {
        return window.forge.ajax({
          url: "http://devbuildinglynx.apphb.com/api/authentication?logmeoff=true",
          dataType: "json",
          type: "GET",
          error: function(e) {
            return alert("error logging out");
          },
          success: function(data) {
            return Meshable.vent.trigger("goto:login");
          }
        });
      },
      refPage: function() {
        return $.mobile.changePage($('#ref-page'), {
          changeHash: false,
          transition: 'none',
          showLoadMsg: true
        });
      },
      gateway: function(macaddress) {
        Meshable.currentMac = macaddress;
        return Meshable.vent.trigger("goto:nodes", macaddress);
      },
      gateways: function() {
        return Meshable.vent.trigger("goto:gateways");
      },
      search: function() {
        return Meshable.vent.trigger("goto:search");
      },
      menu_back_btn: function() {
        return $("#popupPanel").popup("close");
      },
      popupPanel: function() {
        return $("#popupPanel").popup("open");
      },
      back: function() {
        return window.history.back();
      },
      home: function() {
        return Meshable.vent.trigger("goto:login");
      },
      dashboard: function() {
        return Meshable.vent.trigger("goto:dashboard");
      },
      menu: function() {
        var h;

        $("#popupPanel").on({
          popupbeforeposition: function() {}
        });
        h = $(window).height();
        $("#popupPanel").css("height", h);
        $("#popupPanel").bind({
          popupafterclose: function() {
            return Meshable.vent.trigger("menu:close");
          }
        });
        $("#popupPanel").popup("open");
        $("#menu_back_btn").tap(function() {
          return $("#popupPanel").popup("close");
        });
        return $("#menu_search_btn").tap(function() {
          $("#popupPanel").popup("close");
          return window.setTimeout((function() {
            return Meshable.vent.trigger("open:search");
          }), 600);
        });
      },
      changePage: function(page, direction) {
        $(page.el).attr("data-role", "page");
        $(page.el).attr("data-theme", Meshable.theme);
        return $.mobile.changePage($(page.el), {
          changeHash: true,
          reverse: direction,
          transition: "none"
        });
      },
      initialize: function() {
        this.firstPage = true;
        return this.firstDash = true;
      }
    });
    return Routing;
  });

}).call(this);
