// Generated by CoffeeScript 1.6.2
(function() {
  define(['jquery', 'backbone', 'underscore', 'marionette', 'Meshable', 'Events'], function($, Backbone, _, Marionette, Meshable, Events) {
    var dashboard, dashboardView, dashboards, dashboardsView;

    dashboard = Backbone.Model.extend({
      initialize: function() {
        return this.set({
          trafficlight: Meshable.chooseLight(this.get('trafficlight'))
        });
      },
      defaults: {
        channelname: "Energy Costs",
        status: "",
        address: "123 Main St.",
        value: "1100.50",
        pre: "$",
        post: "",
        trafficlight: "green"
      }
    });
    dashboards = Backbone.Collection.extend({
      model: dashboard,
      url: function() {
        return Meshable.rooturl + "/api/dashboard";
      },
      initialize: function(dashboards) {
        return this.fetch();
      }
    });
    dashboardView = Backbone.Marionette.ItemView.extend({
      template: '#dashboarditem-template',
      tagName: 'li'
    });
    dashboardsView = Backbone.Marionette.CompositeView.extend({
      itemView: dashboardView,
      template: "#dashboard-template",
      itemViewContainer: "ul"
    });
    return myvent.on("router:appStart", function() {
      var dashboardCompositeView, dashboardsCollection;

      Meshable.loginRegion.close();
      Meshable.addRegions({
        themeRegion: "#csstheme",
        headerRegion: "#header",
        col1Region: ".col1",
        col2topRegion: ".col2top",
        col2bottomRegion: ".col2bottom",
        col3Region: ".col3",
        col4Region: ".col4",
        footerRegion: "#footer"
      });
      $('#header').css('display', 'block');
      $('#footer').css('display', 'block');
      $('.colmask').css('display', 'block');
      dashboardsCollection = new dashboards;
      dashboardCompositeView = new dashboardsView({
        collection: dashboardsCollection
      });
      Meshable.col1Region.show(dashboardCompositeView);
      Meshable.themeRegion.show;
      Meshable.headerRegion.show;
      Meshable.col2topRegion.show;
      Meshable.col2bottomRegion.show;
      Meshable.col3Region.show;
      Meshable.col4Region.show;
      return Meshable.footerRegion.show;
    });
  });

}).call(this);
