// Generated by CoffeeScript 1.6.2
(function() {
  require(["jquery", "async", "backbone"], function($, Backbone, async) {
    return $(document).on("mobileinit", function() {
      $.mobile.linkBindingEnabled = false;
      return $.mobile.hashListeningEnabled = false;
    });
  });

  require(['jqmglobe', 'jqm', "underscore", "marionette", "Meshable", "Router", "Events", "login", 'dashboard', 'search', 'animate', 'slide', 'menu', 'gateways', 'nodes', 'node', 'units'], function(jqmglobe, jqm, _, Marionette, Meshable, Router, Events, login, dashboard, search, animate, slide, menu, gateways, nodes, node, units) {
    return $(document).ready(function() {
      Meshable.events = Events;
      Meshable.router = new Router();
      Backbone.history.navigate("", {
        replace: true,
        trigger: true
      });
      return Meshable.start({
        authModel: "login"
      });
    });
  });

}).call(this);
