// Generated by CoffeeScript 1.3.3
(function() {

  define(['jquery', 'jqm', 'backbone', 'underscore', 'marionette', 'meshable', 'login', 'dashboard'], function($, jqm, Backbone, _, Marionette, Meshable, login, dashboard) {
    var Events;
    Events = new Backbone.Marionette.EventAggregator;
    Events.on("rerender:login", function() {
      $.mobile.changePage($('#splash'), {
        changeHash: false,
        transition: 'none',
        showLoadMsg: false
      });
      Meshable.loginRegion.close();
      Meshable.loginRegion.show(login);
      $("#password-input").hide();
      return $.mobile.changePage($(login.el), {
        changeHash: false,
        transition: "none",
        showLoadMsg: true
      });
    });
    Meshable.vent.on("open:search", function() {
      return Backbone.history.navigate("search", {
        trigger: true,
        replace: false
      });
    });
    Meshable.vent.on("click:menu", function() {
      $("#popupPanel").on({
        popupbeforeposition: function() {
          var h;
          h = $(window).height();
          return $("#popupPanel").css("height", h);
        }
      });
      $("#popupPanel").bind({
        popupafterclose: function() {
          return Meshable.vent.trigger("menu:close");
        }
      });
      $("#popupPanel").popup("open");
      $("#menu_back_btn").tap(function() {
        return $("#popupPanel").popup("close");
      });
      return $("#menu_search_btn").tap(function() {
        $("#popupPanel").popup("close");
        return window.setTimeout((function() {
          return Meshable.vent.trigger("open:search");
        }), 600);
      });
    });
    Meshable.vent.on("menu:close", function() {
      Backbone.history.navigate(Meshable.currentpage, {
        replace: true,
        trigger: false
      });
      return window.history.back();
    });
    Meshable.vent.on("go:back", function() {});
    Events.on("start:auth", function() {
      return Meshable.loginRegion.show(Meshable.authview);
    });
    Events.on("start:angrycats", function() {
      return Meshable.loginRegion.show(Meshable.angryCatsView);
    });
    return Events;
  });

}).call(this);
