// Generated by CoffeeScript 1.3.3
(function() {

  define(['jquery', 'jqm', 'backbone', 'marionette'], function($, jqm, Backbone, Marionette) {
    var Meshable;
    $.support.cors = true;
    $.mobile.allowCrossDomainPages = true;
    Meshable = new Backbone.Marionette.Application();
    Meshable.rooturl = "http://devbuildinglynx.apphb.com";
    Meshable.addRegions({
      loginRegion: "#login",
      mainRegion: "#mainR",
      searchRegion: "#searchR"
    });
    $(document).on("click", "#back-btn", function() {
      return window.history.back();
    });
    $(document).bind('pagechange', function() {
      $('.ui-page-active .ui-listview').listview('refresh');
      return $('.ui-page-active :jqmData(role=content)').trigger('create');
    });
    Meshable.on("initialize:after", function(options) {
      $.mobile.ajaxEnabled = false;
      $.mobile.linkBindingEnabled = false;
      $.mobile.hashListeningEnabled = false;
      $.mobile.pushStateEnabled = false;
      $.mobile.loader.prototype.options.text = "loading";
      $.mobile.loader.prototype.options.textVisible = false;
      $.mobile.loader.prototype.options.theme = "a";
      $.mobile.loader.prototype.options.html = "";
      return Backbone.history.start;
    });
    Meshable.chooseLight = function(light) {
      if (light === "green") {
        return "https://s3.amazonaws.com/LynxMVC4-Bucket/green-light.png";
      } else if (light === "yellow") {
        return "https://s3.amazonaws.com/LynxMVC4-Bucket/yellow-light.png";
      } else if (light === "red") {
        return "https://s3.amazonaws.com/LynxMVC4-Bucket/red-light.png";
      } else {
        return "https://s3.amazonaws.com/LynxMVC4-Bucket/no-light.png";
      }
    };
    return Meshable;
  });

}).call(this);
