// Generated by CoffeeScript 1.3.3
(function() {

  require(["jquery", "jqm-config", 'jqm', 'cordova', "backbone", "underscore", "marionette", "Meshable", "Router", "Events", "login", 'dashboard', 'search'], function($, jqm_config, jqm, cordova, Backbone, _, Marionette, Meshable, Router, Events, login, dashboard, search) {
    return $(document).ready(function() {
      Meshable.events = Events;
      Meshable.router = new Router();
      return Meshable.start({
        authModel: "login"
      });
    });
  });

}).call(this);
